### PR TITLE
Example Full CI/CD example with CF and Discord webhooks

### PR DESCRIPTION
**Pull request by Macleykun**
https://github.com/Macleykun/Future-MC/blob/patch-1/.github/workflows/pull_requests.yml

### CODE REVIEW

**Comment by Macleykun** [comment]
sorry in a hurry, curious what ya think of this so far!

**Comment by itsmeow** [comment]
Looks alright.

**Comment by Macleykun** [comment]
Great! I’ll work on it later today and specify more clearer what users need to change for this to work.

the PR version also is done and will include it later aswell! It had a bug that secrets don’t get passed to forks, so I had to remove a part which isn’t needed anyways for this example!

**Comment by itsmeow** [comment]
That's not a bug, Github Actions secrets cannot be passed to forks or generally triggered through pull requests without prior approval due to security concerns.

**Comment by Macleykun** [comment]
> That's not a bug, Github Actions secrets cannot be passed to forks or generally triggered through pull requests without prior approval due to security concerns.

Where’s that approval normally granted? Then I can pass that to my friends repo!

**Comment by Macleykun** [comment]
What you think of this? You have any feedback :-) ?

**Comment by itsmeow** [comment]
> Where’s that approval normally granted? Then I can pass that to my friends repo!

https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

> What you think of this? You have any feedback :-) ?

idk, I find it quite messy and big for no reason. The action is not designed to provide a full CI workflow - just the ability to upload a file to CF. I like the idea, but I find your implementation quite messy

**Comment by Macleykun** [comment]
How so? It compiles and notifies trough a web hook, and if a commit starts with Release it’ll gather info to fill in the details

I had to use env vars because i had to submit the input and I wanted to do it in a flexible way

what would you change to improve it? I sadly lack programming knowledge for the used actions

**Pull request closed without merging**
